version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4500:80"
    volumes:
      - /dist/andrew-store/browser
    environment:
      - NODE_ENV=production

